#!/bin/bash

############
#  $1 - start number
#  $2 - end number
#  $3 - filename
#  $4 - width
#  $5 - height
#  $6 - paddingTop
#  $7 - Font Size pixels
#  $8 - Alpha
#  $9 - background color
#  $10 - text color
#


for ((i = $1 ; i <= $2 ; i++)); do
   text2png -t "$i" -o $3-`printf "%04d" $i`.png -w $4 -h $5 --paddingTop $6 --font "$7px Arial" -b \#1a427d -c \#e3cd0b -a center --alpha $8
done
